### ISSUE TITLE
Silky's Engine

### ISSUE THREAD

**Issue by vnlovers** [marcussacana/SacanaWrapper#7]
Please add support .mes script from this game https://vndb.org/v20860

**Comment by Gygarde** [comment]
Excuse me, @marcussacana do you have planned to add [Nanairo Reincarnation](https://vndb.org/v15473) to your Specific Games repository? It uses Silky's Engine too. I'm asking here before opening a pointless issue.

Thank you.

**Comment by marcussacana** [comment]
Haha, if you know how big is my list of games to work right now...
Well, this game is one of my targets, but will take a time.

**Comment by Gygarde** [comment]
lol, no problem. I just didn't want to open an issue if you will work on it anyway. Thank you.

**Comment by marcussacana** [comment]
I just come to say: Soon™
5 Games left in my list to do.

**Comment by Gygarde** [comment]
Great! Almost there.

**Comment by marcussacana** [comment]
about the Hikari no Umi no Apeiria, can you upload in a good host like gdrive or onedrive and send to my email the link?, my email is: ddtank.marcus@gmail.com
i'm with some problems to download it.

**Comment by marcussacana** [comment]
Forget, I found one in the mega

**Comment by marcussacana** [comment]
@vnlovers looks like with this engine I will need do a Specific-Game patch like the @Gygarde asked, the script of this engine have the text side-by-side with the opcodes of the script, basically, my so called "edit-to-corrupt script style", and this is a pain to write a proper tool because require a reverse engenering of the script to create a tool that can fully dissassembly the script, so the path will be use the SRL, but maybe I can write a Read Only tool to the sacana wrapper that will allow extract the text to use with SRL.

**Comment by Gygarde** [comment]
Sounds like a pain, tbh. I was reading this engine is really a problem, so may have bugs, yeah?

**Comment by vnlovers** [comment]
Thank you for dedicating your time and energy into this. This repository https://github.com/Inori/FuckGalEngine/tree/master/Silky/MesTool seems to help but I have some problems like I can't insert latin characters.

**Comment by marcussacana** [comment]
maybe a side effect of the script encryption, this happen in games of the circus engine have a problem like this too...
Anyway about the question of the @Gygarde, maybe the SRL run stable maybe not, we only will know after I patch the game... the SRL can make some games unstable usually because is written in C# and the CLR is injected to can run the SRL and this is bad to some games

**Comment by marcussacana** [comment]
Looks like the SRL isn't compatible with this engine because of the encryption :( 
well, I will give a look in the inori tool by now, If I feel necessary maybe rewite to C# and inlcude in the sacanawrapper.

**Comment by Gygarde** [comment]
That's a shame. Hope you can do something with it, Silky's games looks great. Thanks for your efforts.

**Comment by marcussacana** [comment]
@vnlovers you said the inori tool don't support latin characters, but are you saying about the latin alphabet or special characters like çãéí and etc?

**Comment by vnlovers** [comment]
> @vnlovers you said the inori tool don't support latin characters, but are you saying about the latin alphabet or special characters like çãéí and etc?

Just latin alphabet. But if you can insert special characters it will be much better.

**Comment by marcussacana** [comment]
After Take a proper look, well guys, as I thought, this shitty encryption make the utf16 useless because like the circus he subtract a value from the string bytes, then to make possible use those character I will need use the SRL char reloader feature or brick the encryption algorithm and convert decrypt all scripts

**Comment by marcussacana** [comment]
First I will try brick the encryption because looks like this engine use UTF16, and this means will automatically support translation to all languages, but if the game became unstable i will try the SRL.

**Comment by Gygarde** [comment]
Fingers crossed!

**Comment by marcussacana** [comment]
@vnlovers you know any translation patch to this engine that used this mestool? 
Looks like this mestool as created to works only with games after you brick the encryption algorithm of the engine, if this is the case I need take a look how they did that to make the tool compatible.

**Comment by marcussacana** [comment]
Forget, looks like this tool is to a chinese project, then they don't need brick the engine like us, then will be useless take a look in their patch.

**Comment by marcussacana** [comment]
hmm, i'm wrong, the engine don't use utf16, i thought because I saw the engine using ax instead al in the disasm, well, this don't change anything, just will required a font modding to works...

**Comment by marcussacana** [comment]
Not yet but not so far :)
![image](https://user-images.githubusercontent.com/10576957/69835514-e8127a80-1220-11ea-9043-9dd181a53fda.png)

**Comment by marcussacana** [comment]
Hell Yeah, the pain is, We need patch manually every single release of this engine before translate, If everything works stable, I will try make a small tutorial how to patch is for future reference.
![image](https://user-images.githubusercontent.com/10576957/69836861-72aba780-122a-11ea-80e3-ae0666ca1494.png)

**Comment by marcussacana** [comment]
Then let's go, The patching tutorial.
1 - Open the Aperia.exe with IDA PRO
2 - Wait the IDA PRO analyze the game (Usually the assembly graph mode will begin when finish)
3 - Go to Search => Imediate Value
![image](https://user-images.githubusercontent.com/10576957/69839900-3b43f780-1238-11ea-9456-d871c4018eb0.png)
4 - Type "0x7D62", check the "Find all ocurrences" and press "OK"
![image](https://user-images.githubusercontent.com/10576957/69839947-72b2a400-1238-11ea-87fd-f60be8a5841b.png)
5 - Search for the result like "mov ???, 0x7D62" and double click it.
![image](https://user-images.githubusercontent.com/10576957/69839991-a7bef680-1238-11ea-8433-8f4f979f9939.png)
- Cool, now you can see the game decrypt function...
![image](https://user-images.githubusercontent.com/10576957/69840433-45ff8c00-123a-11ea-9ded-c808199203f3.png)

6 - Open the game with x64dbg.exe (Because is more easy to patch)
7 - Click in "Run" one time and confirm you can see the "EntryPoint" as in the screenshot
![image](https://user-images.githubusercontent.com/10576957/69840118-2ddb3d00-1239-11ea-823a-7990363fe72a.png)
8 - Right Click in the code and Go to Search For => Current Module => Command
![image](https://user-images.githubusercontent.com/10576957/69840480-747d6700-123a-11ea-94c1-b36597b5af98.png)
9 - Type the command that you found in the IDA PRO in the x64dbg
![image](https://user-images.githubusercontent.com/10576957/69840512-9d056100-123a-11ea-98a2-b93229fcb5d1.png)
- You just need remove the 'h' in the end and put '0x' in the begin of the number, like this:
![image](https://user-images.githubusercontent.com/10576957/69840562-cc1bd280-123a-11ea-9a62-0e9b8471634e.png)

10 - Double click the search result
![image](https://user-images.githubusercontent.com/10576957/69840620-eeadeb80-123a-11ea-9305-600b625ad5c1.png)

11 - The x64dbg will select instruction that you searched to you
- After that you will notice a call instruction close with the "mov ???, 0x7D62"^
![image](https://user-images.githubusercontent.com/10576957/69841056-8fe97180-123c-11ea-9426-e08005c6702b.png)

12 - select this call instruction and press 'enter' to open it
![image](https://user-images.githubusercontent.com/10576957/69841105-b7d8d500-123c-11ea-9dba-2654a53380be.png)
13 - Press ":" in your keyboard to give a name to the function
- I will give the name "CopyBuffer"
![image](https://user-images.githubusercontent.com/10576957/69841141-dfc83880-123c-11ea-9c96-42757fb33076.png)

14 - Click it at "OK" and press the `-` key in your keyboard to return to our function
15 - Scroll up to our "mov ???, 0x7D62" again
16 - look in the left part of the disasm code and found the first 'far' jump after our "mov ???, 0x7D62"
![image](https://user-images.githubusercontent.com/10576957/69841683-f66f8f00-123e-11ea-8d0c-52ef0e225a20.png)
17 - Select the jmp (in this case `ja` ) instruction, and press enter to see where he decrypt the byte
- This `sub XX, YY` is what make impossible to translate
![image](https://user-images.githubusercontent.com/10576957/69841752-3df61b00-123f-11ea-901a-b5072b4694d1.png)

18 - Select that `sub XX, YY` and give a right click into him, select Binary => Fill with NOP
![image](https://user-images.githubusercontent.com/10576957/69841818-844b7a00-123f-11ea-8364-fb30127bdfcc.png)
19 - Press OK
![image](https://user-images.githubusercontent.com/10576957/69841845-988f7700-123f-11ea-8f19-75e1e32544aa.png)
- Now you will see that `sub XX, YY` is removed,  
but now we need fix a problem that we caused with this change,  
then take a look in the call CopyBuffer close where we removed the `sub XX, YY`
![image](https://user-images.githubusercontent.com/10576957/69841935-06d43980-1240-11ea-9f8f-1f49c790c935.png)

20 - Search for the next CopyBuffer (2nd after where we removed the `sub XX, YY`)
- You can see we have a second CopyBuffer very close with the first, and before of this call,
we have a `cmp XXX, YYY` instruction in both CopyBuffer
![image](https://user-images.githubusercontent.com/10576957/69842057-8cf08000-1240-11ea-80d0-10de17683efb.png)

21 - Select the second  `cmp XXX, YYY` instruction and press `:` to give a name to the instruction
- I will give the name "PutLowToBuffer" to this part of the fuction
![image](https://user-images.githubusercontent.com/10576957/69842519-59aef080-1242-11ea-9c3b-a7201ce998c6.png)

22 - Select the jmp of the first CopyBuffer
![image](https://user-images.githubusercontent.com/10576957/69842639-c629ef80-1242-11ea-8a74-d058cdefa15c.png)

23 - Press space and type `jmp PutLowToBuffer` (if you put other name before you need change it here too)
-  Check the "Fill With Nop's" too
![image](https://user-images.githubusercontent.com/10576957/69842708-05584080-1243-11ea-881e-d89ab99e6cb6.png)

- This is how will look like our final result
![image](https://user-images.githubusercontent.com/10576957/69842747-2e78d100-1243-11ea-98ab-e43a90373715.png)

24 - Press CTRL + P and click at "Patch File"
![image](https://user-images.githubusercontent.com/10576957/69842779-4f412680-1243-11ea-8a7a-b59893e06b77.png)

25 - Save your new patched executable and enjoy :) 
![image](https://user-images.githubusercontent.com/10576957/69842809-74359980-1243-11ea-8a9b-7f08b78375ff.png)

**Comment by marcussacana** [comment]
Can looks hard, but I did a step-by-step tutorial, I think everyone can do this with a little of patience.

**Comment by Gygarde** [comment]
Wow, seems a bit complicated. Would be the same for Nanairo?

**Comment by marcussacana** [comment]
Probably, but isn't impossible to change too.

**Comment by marcussacana** [comment]
PDF Version of the tutorial, the screenshot image can became offline one day, then... [Silky Patching Tutorial.pdf](https://github.com/marcussacana/SacanaWrapper/files/3903725/Silky.Patching.Tutorial.pdf)

**Comment by Gygarde** [comment]
I was practicing with Nanairo, I've patched the file but idk what to do now lol.

**Comment by marcussacana** [comment]
Well, if you patched you just need use the mestool given by the @vnlovers and will works...

**Comment by marcussacana** [comment]
Here, the compiled tool to you with a .bat that you just need drag&drop the directory with the scripts
[Mestool.zip](https://github.com/marcussacana/SacanaWrapper/files/3903764/Mestool.zip)

**Comment by marcussacana** [comment]
to extract the script you can use the [GARBro](https://github.com/morkt/GARbro), and you don't need repack, just drop translated .mes script to the game directory and he will read it, like the BGI engine.

**Comment by Gygarde** [comment]
Ah, that's why I was talking about SRL, those tools does not work with Nanairo. I just get this from all scripts:
![imagen](https://user-images.githubusercontent.com/38927751/69844321-0fc60a80-1242-11ea-8263-ba2018b505ee.png)

**Comment by marcussacana** [comment]
I see, then I will have more work with the nanairo... then in your case you will need wait a little more... maybe I can need create my own version of the mestool to this....

**Comment by Gygarde** [comment]
No problem!

**Comment by marcussacana** [comment]
@vnlovers you can get the patch to the Apeiria here: https://github.com/marcussacana/Specific-Games/blob/master/Stuff's/Hikari%20no%20Umi%20no%20Apeiria.rar
Now your request is clear, then in the next time I have time I will work with the nanairo.

**Comment by marcussacana** [comment]
@Gygarde I tried do a small fix to the mestool, try it: [mestool-nanairo.zip](https://github.com/marcussacana/SacanaWrapper/files/3906293/mestool-nanairo.zip)

**Comment by Gygarde** [comment]
@marcussacana yep, working. Just need a way to redirect the font.

**Comment by marcussacana** [comment]
@Gygarde try it: https://github.com/marcussacana/Specific-Games/blob/master/Stuff's/Nanairo%20Reincarnation.rar
By default using my gothic modded, if you don't know this the remap of my font: [Gothic Modded.txt](https://github.com/marcussacana/SacanaWrapper/files/3906341/Gothic.Modded.txt)

**Comment by marcussacana** [comment]
I think this case is closed... any problem open the issue again.

**Comment by marcussacana** [comment]
@Gygarde  and @vnlovers more good news,
Using the nanairo script as reference I did a update to the mestool that maybe will works without patch the game executable, here: 
[mestool 0x0B.zip](https://github.com/marcussacana/SacanaWrapper/files/3906718/mestool.0x0B.zip)
After take a look in the nanairo I saw he using a different opcode (0x0B) that don't encrypt the dialogue, and this caused the old mestool don't works, Then I updated the tool but after a proper look, looks like this same 0x0B opcode is supported by the aperia too, so I think this make my all work to patch the exe useless, this is a little sad to me but whatever...

And more one update :) This one I recommend you test it before release your patch because  I can't ensure this my version is stable due big changes in the tool, unfortally i'm not a C++ dev, then it's better don't trust much in this my version....
And what this my version do? basically accept breaklines!
![image](https://user-images.githubusercontent.com/10576957/69895431-0a35f680-130e-11ea-8b7a-24cc4ae4ec5c.png)

Then, it's here my version: 
[mestool-breakline.zip](https://github.com/marcussacana/SacanaWrapper/files/3906719/mestool-breakline.zip)

I thought in add support to the furigana too, but this will require more complex changes in the tool and will be more uncertain about the stability....
![image](https://user-images.githubusercontent.com/10576957/69895450-744e9b80-130e-11ea-9b60-b2d094a55d9a.png)

**Comment by Gygarde** [comment]
I'm getting 0xc000007b error with breakline.zip. Idk why, I have Microsoft Visual C++ 2010.

**Comment by marcussacana** [comment]
when extract or insert?

**Comment by Gygarde** [comment]
Extracting and inserting, hahaha

**Comment by marcussacana** [comment]
give me a screenshot of the error.

**Comment by Gygarde** [comment]
Looks like I need some DLL, do you know what package has msvcp140d and vcruntime140d?
![imagen](https://user-images.githubusercontent.com/38927751/69895666-fb9a1000-130a-11ea-8733-0a461fee9a8a.png)

**Comment by marcussacana** [comment]
yeah, missing c++ redist packages, try install the 2015 c++ redist

**Comment by marcussacana** [comment]
anyway I found a strange bug, the insert crash after add new lines for some reason...

**Comment by Gygarde** [comment]
Then I'll just wait for you to fix it. I was checking and I have C++ packages. I don't remember installing those packages but welp.

![imagen](https://user-images.githubusercontent.com/38927751/69895916-e4f5b800-130e-11ea-8c7d-20edcb091b13.png)

**Comment by marcussacana** [comment]
well then download the dll manually, search the name in the google, you will found the dll to download easy

**Comment by marcussacana** [comment]
bugfix: [mestool-breakline.zip](https://github.com/marcussacana/SacanaWrapper/files/3906761/mestool-breakline.zip)

**Comment by marcussacana** [comment]
Working like a charm now, this is the first dialogue after the new game, have 2 lines only
![image](https://user-images.githubusercontent.com/10576957/69896109-322b5700-131a-11ea-8443-3935d10cc154.png)

**Comment by marcussacana** [comment]
More one fix: [mestool-breakline.zip](https://github.com/marcussacana/SacanaWrapper/files/3906788/mestool-breakline.zip)

**Comment by Gygarde** [comment]
I tried what you told and... 

![imagen](https://user-images.githubusercontent.com/38927751/69897469-f2b53880-1322-11ea-919c-1987f6b7d395.png)

I've reinstalled packages and nothing. I'll check it later. Thanks for fixing the tool!

**Comment by marcussacana** [comment]
when you downloaded the dll, you need check if you used similar versions and arch, anyway, that my first build worked to you? if yes I think i can 'fix' this here just using the old build toolset

**Comment by marcussacana** [comment]
More fix :) this time fix a original problem of the tool: [mestool-breakline.zip](https://github.com/marcussacana/SacanaWrapper/files/3907110/mestool-breakline.zip)

**Comment by Gygarde** [comment]
@marcussacana yep, I checked. And yes, all versions until and including **mestool 0x0B.zip** are working fine.

**Comment by marcussacana** [comment]
yeah, i builded manually using the cl command, that version with error to you I builded with VS2019

**Comment by Gygarde** [comment]
Many thanks, really!

**Comment by Gygarde** [comment]
Hey, @marcussacana, sorry for being a pain. I'm also planning an all-ages version (includes ps vita content), but the +18 exe is not compatible, can you add the font redirect to this exe too?
 
[nanairo ps_vita.zip](https://github.com/marcussacana/SacanaWrapper/files/4145267/nanairo.ps_vita.zip)

Thank you.

**Comment by marcussacana** [comment]
I will take a look soon

**Comment by marcussacana** [comment]
@Gygarde sorry for make you wait, I rewrited my StringReloads from the zero,  
then I need a time since I wanted make my new version of the SRL works to any  
new tool by me, anyway, here: [NPV.zip](https://github.com/marcussacana/SacanaWrapper/files/4272433/NPV.zip)  
I don't tested it, if don't work as expected just say.

**Comment by Gygarde** [comment]
Working, thank you. Also, I wanted to ask you about it. Nanairo scripts are in ANSI, but putting symbols like m**ﾁ**s needs Shift-JIS, so I have to set it every time. Any way to automatically change it from ANSI to Shift-JIS?

![imagen](https://user-images.githubusercontent.com/38927751/75634694-48310800-5be6-11ea-98e5-d3a841ee4574.png)

**Comment by marcussacana** [comment]
Are you saying about your text editor?
Are you using the notepad or notepad++?
And well, https://github.com/marcussacana/StringReloads/tree/DotNetFramework/SRLTracer
This old tool can automatically replace the japanese characters in the text file, for now I didn't writed something like that to the new SRL.
And maybe the 010Editor can help because he save the lastest encoding and didn't change automatically.

**Comment by Gygarde** [comment]
I'm using Notepad++. Tried with 010 editor, works better for this novel. Thank you! Hope no more major bugs from here, this engine is really something, haha. 

You can close the issue, I'll let you know if something goes wrong with SRL.

**Comment by Gygarde** [comment]
Hi again, @marcussacana! Just a question, no need to open this issue again. Do you know something about the AKB images in this engine? Garbro can open them, but repacking is another story though. 

I checked Inori repo and found [this](https://github.com/Inori/FuckGalEngine/tree/master/Silky/AkbTool). But I couldn't make it work (error_writing_png) with unpack and repack. Maybe I broke something trying to compile. Can you take a look, please?

[LOGO.zip](https://github.com/marcussacana/SacanaWrapper/files/4465907/LOGO.zip)

**Comment by marcussacana** [comment]
I have no idea, usually I don't work with images, I can give a try but i'm very busy those days, so will take a time.

**Comment by kazurabakouta** [comment]
You made fantastic tool.
Any chance for you to add support to this game [https://vndb.org/v11343](url)? I tried using mestool from this thread, while It can extract, I think there's problemduring insertion since most of the edited script came out as 0kb empty or froze the game after patching. 
It run on AIN6WIN engine just like earlier Silky's game so you may find many similarity with Elf's game engine.
Many thanks and much appreciated.

**Comment by Gygarde** [comment]
@marcussacana also reporting the modified tool does not work with https://vndb.org/r71401
All extracted files are empty. [Here's a sample](https://cdn.discordapp.com/attachments/529475786160472077/712437678640988220/script.rar). Take a look when you have time.

**Comment by NguyenLucMinhThong** [comment]
im use arc_unpacker to unpack script.arc file, have MES files, edit it and how to pack it again or how to use edit file?
